### ISSUE TITLE
Create a showcase for a controlled editor

### ISSUE THREAD

**Issue by charlex** [ifiokjr/remirror#116]
## Description

I mentioned in https://github.com/ifiokjr/remirror/issues/23 that I was attempting to try my hand at creating a controlled editor, and looking for guidance from the documentation. I'm going to post my code below to see if this is either helpful for people on a similar path to me, and also see if anyone who has been down this path can help.

My usecase is that I'd like the user to be able to click a button outside of the editor, and the editor to respond with an updated value. Essentially, an HTML string should be turned into a state object for prose mirror. 

## Blocker

This code is a work in progress, and is not yet functional.

I am getting this error:

```
Uncaught TypeError: _this.state.newState.applyTransaction is not a function
    at EditorView.<anonymous> (react.esm.js:608)
    at EditorView.dispatch (index.js:4637)
    at readDOMChange (index.js:2576)
    at DOMObserver.handleDOMChange (index.js:3013)
    at DOMObserver.flush (index.js:2959)
    at MutationObserver.DOMObserver.observer (index.js:2874)
```

## Proposed

I've based this code off of the [markdown/wysiwg editor showcase](https://github.com/ifiokjr/remirror/tree/master/@remirror/editor-markdown/src/editor.tsx).

```jsx
import { logger } from '@myOrg/utils';
import {
  createDocumentNode,
  EditorState,
  ProsemirrorNode,
} from '@remirror/core';
import { BoldExtension, LinkExtension } from '@remirror/core-extensions';
import {
  ManagedRemirrorProvider,
  RemirrorExtension,
  RemirrorManager,
  RemirrorManagerProps,
  RemirrorProviderProps,
  useRemirrorManager,
} from '@remirror/react';
import React, { FC, ReactElement, useEffect } from 'react';
import { useSetState } from 'react-hanger';
import { MirrorEditorInner } from './MirrorEditorInner';

export type InternalEditorProps = Omit<
  RemirrorProviderProps,
  'childAsRoot' | 'children'
>;

interface IMirrorEditorProps {
  value: string;
  onChange: (val: string) => void;
  disabled?: boolean;
}

const defaultPlaceholder: RemirrorManagerProps['placeholder'] = [
  'Start typing...',
  {
    color: '#aaa',
    fontStyle: 'normal',
    fontWeight: 300,
    letterSpacing: '0.5px',
    position: 'absolute',
  },
];

interface IMirrorEditorProviderProps extends IMirrorEditorProps {
  children: ReactElement;
}

const MirrorEditorProvider: React.FC<IMirrorEditorProviderProps> = ({
  children,
  value,
  disabled,
  onChange,
  ...props
}) => {
  const { schema } = useRemirrorManager();
  const initalContent = createDocumentNode({ content: value, schema });
  const raw = useSetState<ProsemirrorNode>(initalContent);
  const editor = useSetState<EditorState<any>>(null);

  useEffect(() => {
    editor.setState({
      ...editor.state,
      doc: createDocumentNode({ content: value, schema }),
    });
  }, [value]);

  return (
    <>
      <ManagedRemirrorProvider
        onStateChange={({ newState, getText }) => {
          logger.info('onStateChange', { text: getText() });
          editor.setState(newState);
          raw.setState(newState.doc);
          onChange(getText());
        }}
        value={editor.state}
        initialContent={raw.state}
        withoutEmotion
        editable={!disabled}
      >
        {children}
      </ManagedRemirrorProvider>
    </>
  );
};

export const MirrorEditor: FC<IMirrorEditorProps> = props => {
  return (
    <RemirrorManager placeholder={defaultPlaceholder}>
      <RemirrorExtension Constructor={BoldExtension} />
      <RemirrorExtension Constructor={LinkExtension} />
      <MirrorEditorProvider {...props}>
        <MirrorEditorInner />
      </MirrorEditorProvider>
    </RemirrorManager>
  );
};
```

```
import { faBold } from '@fortawesome/pro-light-svg-icons';
import { logger, Button } from '@myOrg/utils';
import { useRemirror } from '@remirror/react';
import React, { FC } from 'react';

export const MirrorEditorInner: FC<IProps> = ({}) => {
  const { getRootProps, actions } = useRemirror();
  return (
    <div className="mirror-outer">
      <div className="mirror-menu">
        <Button
          active={actions.bold.isActive()}
          disabled={!actions.bold.isEnabled()}
          onClick={() => {
            actions.bold.command();
          }}
          icon={faBold}
        />
      </div>

      <div {...getRootProps()} className="mirror-root" />
    </div>
  );
};
```

--

I will throw this into one of those great code sandbox tools out there so that others can reproduce.

**Comment by ifiokjr** [comment]
@charlex I'll look into the bug 👍 

Please be aware that the markdown editor code is more like pseudo-code at the moment. I haven't tried running it before so I'm sure it's completely broken.

**Comment by charlex** [comment]
Haha, that would probably explain that, then! Thanks for looking into! This would be great to pull off!

**Comment by benjie** [comment]
@ifiokjr I'd like to help you get the (controlled) markdown editor up and running. I'm hoping that I can spend next Friday working on it (hopefully most of a work day), and maybe some more time the Friday after that. Would this contribution be welcome, and if so would you like to discuss anything before-hand? I'm fairly new to Prosemirror (but am an old-hand at React and JavaScript) so any pointers you wanted to give would be very helpful I'm sure.

Thanks for your work on this project! :pray:

**Comment by ifiokjr** [comment]
@benjie the contribution would be highly appreciated 😄 
Let me know if you need pointers. I'll also try to clean up the code slightly in the meantime 👍

**Comment by benjie** [comment]
Cool; any pointers you can give would be welcome. If you wanted to lay out in broad strokes how you’d go about it, it may make the PR more likely to be what you’re after :)

**Comment by ifiokjr** [comment]
@benjie awesome! I'll get back to you with some pointers during the week.

**Comment by ifiokjr** [comment]
@benjie It's been a pretty busy week. I'm travelling this morning but will send through my thoughts this afternoon.

**Comment by benjie** [comment]
Cool; I'm just starting now so I'll clone it down and start familiarising myself with the codebase. I've got about 3 hours, so today is likely to be more discovery than much in the way of changes.

**Comment by benjie** [comment]
Indeed, I did not get very far. Here's some things I've figured out (other than in the PRs I've raised):

- remove `private: true` from the `@remirror/editor-markdown/package.json` file so that `yarn build` and `yarn dev:modules` can see (and compile) it
- run `yarn build` on a fresh install to build the initial version of everything
- run `yarn dev:modules` in the background to keep everything ticking over
- it looks like the intent of `editor-markdown` was to give an editor that could be either wysiwyg or markdown. Initially I started by trying to fill in the blanks here, but it wasn't sufficiently similar to the wysiwyg editor for me to be able to make the changes. So next up, I decided to try and turn the wysiwyg editor into a controlled editor.
  - `onStateChange` is not a prop that `WysiwygEditor` accepts (though it does accept `onChange` that doesn't make it controlled)
  - `onStateChange` seems to only be accepted on the `<Remirror>` component itself
  - I can't figure out where the `<Remirror>` component is used, other than the tests, since the docs and examples all build editors from the various components. I've not managed to figure out how to apply `onStateChange` to one of these multi-component editors
- the easiest way to test things is to spin the docs up, and then tweak the examples in there, for example I changed `@remirror/showcase/src/wysiwyg.tsx` to have two editors, hoping that I could mirror them but since I couldn't get them working controlled I did not achieve my goal

**Comment by benjie** [comment]
AH! `RemirrorProvider` (which is called by `ManagedRemirrorProvider`) is what ultimately renders `Remirror`; so I just need to pass select props into that provider. Which is what I've done, actually, but I get an error:

![Screenshot_20190809_165752](https://user-images.githubusercontent.com/129910/62792284-d9b01f80-bac6-11e9-9e06-49fd2ebea990.png)

**Comment by benjie** [comment]
Right so here's a controlled component:

https://github.com/ifiokjr/remirror/commit/001059b00b480b7052b0c4a74c16b01430e5b043

The error before was because I didn't realise `onStateChange` was passing a complex object, I was just expecting the newState. The object is super obvious now, since this is how ProseMirror works. It's suddenly starting to come together, right at the end of the day...

When I try to link the two components together I get a "mismatched transaction" error; I think this might be because I'm using an initial null state. Will have to figure out how to get an initial state that's valid for both editors to see if that is indeed the case (but I recall from ProseMirror that the state includes details of the plugins/etc and remirror is handling this, so I'm not sure how best to get an initial state...)

![Screenshot_20190809_170854](https://user-images.githubusercontent.com/129910/62793093-a2db0900-bac8-11e9-8de0-b22aa54f1c0d.png)

**Comment by benjie** [comment]
I've added a new page to the docs for debugging this, on it I've put a controlled editor, and next week I'm going to try and use the `toMarkdown` / `fromMarkdown` to populate the textarea with the markdown live from the editor. If I can get two-way sync working that'd be epic, but it's going to be challenging due to partial syntax matches.

https://github.com/benjie/remirror/commit/4c3dc5ebbfff5d3890c868cbd07f49c0a72ec48a

**Comment by charlex** [comment]
@benjie thank you for your work and the update! Two-way syncing will be a big addition to my usecase of Remirror.

**Comment by benjie** [comment]
@ifiokjr Would it be possible for you to produce a small sandbox example of two synchronised Remirror editors using the controlled interface? Is it even possible, do you think, or do we need to use [the "collab" interface](https://prosemirror.net/docs/ref/#collab) to achieve that? Asking not because I need this for an app, but because it would significantly help me understand how data is flowing through the system and what can/cannot be changed.

**Comment by ifiokjr** [comment]
@benjie I think that's a good idea. 

These last few weeks I've been occupied with integrating `remirror` into a new platform for a company based in the US. Working on it has opened my eyes to several areas which are severely lacking. The main pain point I noticed was implementing a UI around the text editing functionality and I've decided to attack that problem first. 

It's a big chunk of work and I'm not the best at estimating how long something will take but it would make consuming remirror so much simpler and nicer while retaining the flexibility. I should have some code to push up tomorrow to the `ui` branch. 

> or do we need to use [the "collab" interface](https://prosemirror.net/docs/ref/#collab) to achieve that

I don't believe that is required. When I have a spare moment I'll try and get the [`@remirror/editor-markdown`](https://github.com/ifiokjr/remirror/blob/61e434ce14f39ed50d05d0a0318239d7b691e3ba/%40remirror/editor-markdown/src/editor.tsx#L119) working with a limited use case as suggested. 

I took another look at the code and while it currently doesn't run, conceptually it seems to me to be the best way to get the two way syncing to work. 

- There are **two** editors one `markdown` and one `wysiwyg`
- `wysiwyg` is the main editor since we're more interested in the editor state produced specifically for prosemirror
- the markdown editor is a simplified editor with a parent `doc` that only accepts once child node `codeBlock`. The `codeBlock` uses [refractor](https://github.com/wooorm/refractor) (prism) for syntax highlighting.
- every time the user switches from the markdown view to the editor view they are essentially switching editors. 
- on each update, the content of the currently active editor is converted into a state which can be readily consumed by the other editor. This means that switching editors should be seamless https://github.com/ifiokjr/remirror/blob/61e434ce14f39ed50d05d0a0318239d7b691e3ba/%40remirror/editor-markdown/src/editor.tsx#L131-L141  


Currently, the implementation is purely pseudo code. It really shouldn't have made its way into the library 😔 but it did so at a point when I was still unsure of the future of this project.

The reasons it doesn't work could be: 

- `onStateChange` is fundamentally flawed and I've missed out on something obvious. There are currently only [two unit tests](https://github.com/ifiokjr/remirror/blob/61e434ce14f39ed50d05d0a0318239d7b691e3ba/%40remirror/react/src/components/__tests__/remirror.spec.tsx#L139-L195) (one of which is basically just a snapshot test) for the controlled remirror component.
- The untested, unconsumed and low-quality pseudo-code doesn't actually implement what I want it to implement. 

I won't be surprised if it turns out to be both.

**Comment by benjie** [comment]
@ifiokjr Awesome, I look forward to hearing how you progress. I'm back to this for a few hours on Friday again :+1:

**Comment by ifiokjr** [comment]
@benjie I'm looking at it now. I'll add my work to the ui branch which is still in progress, but I feel like I'm ready to tackle the controlled editor part. 

Hopefully, I can get something running before you get started today 🤞

**Comment by ifiokjr** [comment]
@benjie 

### Current Progress

![2019-08-16 10 12 50](https://user-images.githubusercontent.com/1160934/63157375-b7f6f100-c00e-11e9-962b-8dca04ba8137.gif)


There are actually some fundamental bugs that are coming to light though as I work on this. 

- I'm seeing the same transaction error you were seeing which suggests there's a bug in the way `onStateChange` is handled by the `Remirror` component
- CodeBlock decoration for the markdown editor are bleeding into the the wysiwyg portion which is odd
- The `ExtensionManager` is being reinitialized on each switch causing a number of bugs and eventually losing all attributes within the wysiwyg editor state.

**Comment by benjie** [comment]
@ifiokjr Cool, thanks for doing this work. Do you have suggestions on where I should start/focus? The last bullet seems the most serious, but I don't think I have enough context to figure out if/how to solve this.

**Comment by ifiokjr** [comment]
@benjie do you mind I take this one on. I'll include it as part of the next version v0.5.0 with a target release of this Sunday. 

It's just it might take a rewrite around the controlled editor functionality and that's not the easiest place to start as a contributor.

It's a lesson to me about adding functionality without testing the implementation.

**Comment by benjie** [comment]
No problem at all. We're hoping to use Remirror using markdown as the interchange format in our app. Previously we were using DraftJS and had a custom markup (inspired by Slack's markup) for simple text that just had tags/mentions/etc, and we were just storing the DraftJS content object for everything else. We'd like to use Markdown as the interchange format, whilst still allowing features like collaboration - the plan is to use Prosemirror with markdown import/export and to use raw prosemirror transactions with the collaboration plugin when we need that. At this point we're still experimenting with remirror (which seems very promising, and certainly beats us building our own bundle of prosemirror which I had previously started on), and are keen to help get it to production-readiness for our needs.

**Comment by benjie** [comment]
(By the way, the plan is to use "special links" in markdown for the mentions, e.g. `[@benjie](mention://27)` to indicating mentioning user with ID=27. This should enable us to keep to core markdown featureset whilst maintaining WYSIWYG editing.)

**Comment by benjie** [comment]
@ifiokjr Heads up: it's Wednesday I'll be working on this next week rather than Friday.

**Comment by benjie** [comment]
Hey @ifiokjr (is there a better channel for us collaborating?) I'll be looking at Remirror next on 6th September; let me know if there's anything I can do on that day to help move things forward. Thanks for all you do! :pray:

**Comment by ifiokjr** [comment]
Thanks, @benjie I've sent you an email (I think) with my details 😄

**Comment by ifiokjr** [comment]
I had some time today to look at the controlled editor and I think I've managed to fix all the bugs mentioned above. You can watch my progress in #149 

There's still a fair bit of work to go into that branch, but the markdown editor will be part of the next major release. 

![2019-08-26 20 18 49](https://user-images.githubusercontent.com/1160934/63716935-0d1cd900-c83f-11e9-95f0-bf5deeb916b5.gif)

**Comment by benjie** [comment]
This is amazing progress @ifiokjr ─ congratulations!

**Comment by qwwwpp** [comment]
> I had some time today to look at the controlled editor and I think I've managed to fix all the bugs mentioned above. You can watch my progress in #149
> 
> There's still a fair bit of work to go into that branch, but the markdown editor will be part of the next major release.
> 
> ![2019-08-26 20 18 49](https://user-images.githubusercontent.com/1160934/63716935-0d1cd900-c83f-11e9-95f0-bf5deeb916b5.gif)

@ifiokjr  Hi I spend hours trying to figure out how to switch between markdown and Wysiwyg node. This gif shows exactly what I want.
Can you tell me where can I find this code and how to run it?
