### ISSUE TITLE
RangeError: Schema is missing its top node type ('doc') using jest-remirror

### ISSUE THREAD

**Issue by dj0nes** [ifiokjr/remirror#180]
## Description

I get the following error when running the example given in the jest-remirror readme:

```
RangeError: Schema is missing its top node type ('doc')

import { renderEditor } from "jest-remirror"
        | ^
      2 | import { EmojiExtension } from "@remirror/extension-emoji"
      3 | 
      4 | test("emoticons replaced with emoji", () => {

      at Function.compile (node_modules/prosemirror-model/src/schema.js:208:33)
      at Object.<anonymous> (example.spec.ts:1:1)
```

Example repo: https://github.com/dj0nes/jest-remirror-error

I see that similar tests run without issue in the remirror monorepo, but I'm not sure what is different between that setup and mine which would cause this error.

## Checklist

- [x] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/canary/docs/pages/contributing.md

**Comment by ifiokjr** [comment]
I've just verified that this is a bug. 

It's a tricky one though. I've narrowed down the bug to the `jest-prosemirror` library and occurring around the [`prosemirror-test-builder`](https://github.com/ProseMirror/prosemirror-test-builder), but at the moment I'm not sure why. 

One thing I've also been able to do is partially replicate the issue in the library by switching off the module mapper within the tests i.e. testing against the built code rather than the .ts files. It's raised a few other bugs which also need fixing.

I'm working on other deadlines at the moment, but I'll look into it in more detail once I'm able to create some time.

Thanks for raising the bug.
