### ISSUE TITLE
Trouble creating TypeScript extensions (within Next.js SSR)

### ISSUE THREAD

**Issue by jashmenn** [ifiokjr/remirror#59]
My problem is an intersection between `remirror` and module loading (with Next.js). It may not be a bug per-se, but it is something I've only encountered with this library. 

I realize I risk getting this issue closed and told to open it at Next.js, but my hope in posting here is that we can clear up how one should ingest the core types to write extensions in TypeScript.

The core idea: I'm running into a situation where importing modules from e.g. `@remirror/core` the objects are exported classes. But with e.g. the default babel/typescript setup with Next.js, the classes are compiled to function classes, and we get 

```
TypeError: Class constructor NodeExtension cannot be invoked without 'new'
```

Here's some code that shows what I mean:

```tsx
// A Next.js app with Typescript as described here: https://github.com/zeit/next-plugins/tree/master/packages/next-typescript
// pages/index.tsx
import { NodeExtension } from "@remirror/core"; // loads two different modules

class TitlePlaceholder extends NodeExtension {}

console.log("NodeExtension: ", NodeExtension); // is an ES6 `class` during SSR
console.log("TitlePlaceholder: ", TitlePlaceholder); // is a function class

// const a = new TitlePlaceholder();
// gives => TypeError: Class constructor NodeExtension cannot be invoked without 'new'

const Index = () => (
  <div>
    <p>Hello Next.js</p>
  </div>
);

export default Index;
```

You can find [this complete repo here](https://github.com/jashmenn/loading-issue-ignore-this/blob/master/pages/index.tsx).

-----

One thing I tried was using a custom webpack module rule to use `babel-loader` for remirror:

```js
// see: https://github.com/zeit/next-plugins/tree/master/packages/next-typescript
// next.config.js
const webpack = (config, { dev, isServer }) => {
  config.module.rules.push({
    test: /\.js$/,
    include: /node_modules\/@remirror/,
    use: {
      loader: "babel-loader",
      options: {
        presets: [
          [
            "@babel/preset-env",
            {
              debug: true,
              forceAllTransforms: true,
              targets: {
                ie: "11"
              }
            }
          ]
        ]
      }
    }
  });

  return config;
};

const withTypescript = require("@zeit/next-typescript");
module.exports = withTypescript({ webpack });
```
The result is:

* babel classTransformer _runs_ over all remirror classes such as `NodeExtension`
* _however_ the initial SSR still receives a `class` (causing an error)
* but the client-side actually receives `NodeExtension` as a function class (!) (the desired result)
(runnable [branch here](https://github.com/jashmenn/loading-issue-ignore-this/blob/other-ideas/next.config.js))

I know I'm on thin ice asking about this, because at that point it seems to be related to the Next.js SSR.

That said it's a vanilla Next.js setup and I can't help but wonder if these issues could be solved by publishing an ES5-style package. 

If anyone has any suggestions on how to resolve these module issues, I'd be deeply grateful.

**Comment by ifiokjr** [comment]
@jashmenn Thanks for such a well laid out issue and reproduction environment.  I've confirmed that what you've posted is a genuine bug and it's certainly one that this project needs to address. 

### Needed changes

It highlights to me that better testing of how the codebase will actually be consumed is needed. This kinds of problem can be addressed long before it reaches the end user.

I'm thinking an examples folder which both shows off some use-cases but can also be run as part of the CI build. The following would probably be a good start.

- `gatsby`
- `next.js`
- `create-react-app`

Regarding this issue, it's not immediately clear to me how it can be addressed. Looking through the next.js [babel config](https://github.com/zeit/next.js/blob/canary/packages/next/build/babel/preset.ts) I'm not sure what causes it to compile classes down to functions. 

Or is that coming from the webpack config?

### Quick code

I played around with the idea of an **ES5** build for `@remirror/core` and it turns out if I change the`preset-env` to the following:

```js
module.exports {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: '8',
          chrome: '58', // Added
          ie: '11', // Added
        },
      },
    ],
}
```

And also remove `"module": "lib/dist/core.esm.js",` from the package.json file it compiles correctly. 

Note: I needed to remove the module field since it seems that `next.js `webpack config on the browser resolves to use the es6 (modules) build while on the server it sticks to the main build.

![image](https://user-images.githubusercontent.com/1160934/54802247-65cdc180-4c62-11e9-8558-439a4cdef044.png)


###  First impressions

Releasing this library as an ES5 build seems like a drastic step to me since I'm not really planning on supporting older browser versions. The class keyword is widely supported enough to be used for new libraries like this one. This is an important issue though, with some personal bias since I'm actually going to be consuming this library in a `next.js` project soon. That said, I don't want to rush to a solution just yet. 

There are a few API improvements coming and I'll address this issue once I've implemented them. If you have any suggestions or solutions that address it in a more elegant way, I'm certainly open to them.

**Comment by ifiokjr** [comment]
@jashmenn A really quick fix from your end would be to replace your `.babelrc` file with the following.

```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {
          "targets": {
            "node": "8"
          }
        }
      }
    ]
  ],
  "plugins": ["@babel/plugin-transform-typescript"]
}
```

You can see the results in a fork of your reproduction git repository. 

https://github.com/ifiokjr/loading-issue-ignore-this/blob/patch-1/.babelrc

That being said I don't think it's fair to require users to be aware of this implementation detail. The problem is coming from the fact that `remirror`'s babel build sets the preset target to `node: 8`. There's no need for this so I'll change that and publish a new release.

**Comment by ifiokjr** [comment]
@jashmenn this all works now with the latest update. No need to change the babel plugin settings.

You can test it out [here](https://github.com/ifiokjr/loading-issue-ignore-this/tree/patch-2).

**Comment by jashmenn** [comment]
🙏 Thank you _so_ much. I struggled w/ this for hours and your fix works perfectly.

Remirror is amazing, btw! It's a near-perfect structuring of Prosemirror with React. Thanks for sharing it!

**Comment by ifiokjr** [comment]
@jashmenn I've noticed that an unintended side effect of the changes made to fix this bug, is a 30% increase in the size of the `@remirror/core` [library](https://bundlephobia.com/result?p=@remirror/core@0.0.1-alpha.10), from `37.5kb` to `48.8kb`.

I'll keep an eye on this as it may be possible to achieve the desired outcome (build compatibility with next.js and other platforms), without adding the unwanted extra build code.

![image](https://user-images.githubusercontent.com/1160934/55215147-adb79000-51f0-11e9-9ffb-d876f26e5b6f.png)
