### ISSUE TITLE
[Question] how to use an extension?

### ISSUE THREAD

**Issue by dpaez** [ifiokjr/remirror#70]
Hi @ifiokjr, great library by the way I really like your effort mixing up prosemirror with react 👍 

I'm trying to create a markdown editor (using the [markdown schema](https://github.com/ProseMirror/prosemirror-markdown)) but I'm a bit lost. Should I add the schema like a remirror extension?

Thanks in advance!

PS: going beyond if I'm able to create the md editor successfully, the next step would be adding some collaborative capabilities using some P2P stuff.

**Comment by ifiokjr** [comment]
@dpaez thanks for taking the time to create an issue. 

I think there are two questions you're asking

1. How does one create a custom extension?
2. Is it yet possible to create a markdown editor?

### 1. How does one create a custom extension?

Currently, the docs are very poor but you can look through some of the examples for inspiration. There's also a tiny introduction to the concept in the [`@remirror/core` readme](https://github.com/ifiokjr/remirror/blob/master/@remirror/core/readme.md).

### 2. Is it yet possible to create a markdown editor?

I've been thinking lately on how to properly implement a Markdown editor for remirror and it's certainly something that's part of our [**roadmap**](https://github.com/ifiokjr/remirror/issues/1).

It hasn't happened yet due to a current focus on the more foundational elements of `remirror`. However, it is something I'd like to start diving into next week. 

My thoughts so far are on the four options for a markdown editor.

1. A raw text editor which you type markdown into and a preview option which simply renders the markdown into (HTML / JSX). This doesn't need remirror to work.
   
2. Again a markdown editor which is a remirror editor but when markdown is typed, it decorates the following text with a markdown parser. So bold text would still have the markdown `**` but would also look bold to the user. This would be a pseudo-preview. Similar to option one a preview option to view the rendered markdown would also be possible. 
   
3. The ability to write ordinary text and translate the output to markdown. In other words a normal editor with an option to display the markdown. This would mean a to-markdown serializer that takes in the prosemirror content JSON and translates it to a markdown string. 
   
4. A combination of 2 and 3.


Option 4 seems to be where we will be heading.

An editor that allows directly typing in markdown which is automatically wrapped in prosemirror decorations that allow users to see a pseudo-preview. It would need a toggler which allows the user to switch to writing in a non-markdown.  This would receive the currently typed markdown (as text) and transform it into a prosemirror model.  

This would be in fact, two editors. And switching between the two would need to be built into a new UI package e.g. `@remirror/ui-markdown`.

Of course, all the building blocks of this implementation would be available so that developers can customize the editor to suit their own needs.

There's more to it than this, but these are my initial thoughts. 

I'll create an issue with more information in the next few days.

**Comment by ifiokjr** [comment]
Closing as answered.
